### PR TITLE
add analytics script

### PR DESCRIPTION
**Pull request by Bsheridan12**

### CODE REVIEW

**Comment by KYoon** [comment]
Nice. Didn't know someone else was also looking back on this project lol. How exactly do we access the analytics?

**Comment by Bsheridan12** [comment]
Yeah I want to get back into it. This was just a very minor addition.

I added all of us as admins along with the stacks.cards@gmail.com account
to the Analytics and Webmaster tools.

https://www.google.com/analytics/web/?hl=en#report/visitors-overview/a63126624w98501538p102528636/
https://www.google.com/webmasters/tools/home?hl=en

Currently the site stacks.cards is going to the Stack-on-deck.herokuapp.com
site rather than wherever you are pushing the most recent update so I dunno
if we want to change that or what but the site for that is:

https://manage.www.namecheap.com/myaccount/index.asp
Yooniversal
howl@theYoon

**Comment by KYoon** [comment]
Cool. Yeah, if you want to hop back on it, feel free to look at the to-do list on the readme. Some things I have on the top of my head is rejoining, clearing up rooms after a certain amount of time, getting rid of timeouts and replacing with promises, and general refactoring. Also, might want to edit your post and maybe put it into the slack for that information. Other people do have access to see this convo and we don't want them to have the credentials.

**Comment by Bsheridan12** [comment]
Oh haha I thought I was just emailing you. There we go.

**Pull request merged**
